# Generated by Django 3.0.6 on 2020-09-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_course_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='rater',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
