# Generated by Django 3.0.6 on 2020-09-27 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_remove_rater_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rater',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='rater',
            name='rate_on',
        ),
    ]
