# Generated by Django 3.0.6 on 2020-10-01 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_reviewer_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='course.Rater'),
        ),
    ]
