# Generated by Django 3.0.6 on 2020-09-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20200926_1145'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='purchased_courses',
            field=models.ManyToManyField(related_name='purchased_courses', to='course.Course'),
        ),
    ]
