# Generated by Django 3.0.6 on 2020-11-17 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201116_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='course_made_by_me',
        ),
    ]
