# Generated by Django 3.0.6 on 2020-09-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_auto_20200928_1418'),
        ('accounts', '0002_account_purchased_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='purchased_courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='purchased_courses', to='course.Course'),
        ),
    ]
