# Generated by Django 3.0.6 on 2020-09-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_remove_reviewer_rate'),
        ('accounts', '0003_auto_20200928_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='purchased_courses',
            field=models.ManyToManyField(blank=True, related_name='purchased_courses', to='course.Course'),
        ),
    ]
